### ISSUE TITLE
Dead link to compositional sampler paper

### ISSUE THREAD

**Issue by mschauer** [TuringLang/Turing.jl#1094]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_docs/using-turing/guide.md

Dead link in "For more details of compositional sampling in Turing.jl, please check the corresponding paper."

**Comment by cpfiffer** [comment]
Looks like it's at the tail end of [this section](https://github.com/TuringLang/Turing.jl/blob/master/docs/src/using-turing/guide.md#compositional-sampling-using-gibbs). The problem is that previously we appear to be linking to a document on @xukai92's site:

http://xuk.ai/assets/aistats2018-turing.pdf

Is there another place the AISTATS paper is stored?

**Comment by yebai** [comment]
http://proceedings.mlr.press/v84/ge18b.html
