### ISSUE TITLE
Question: Use of the term multivariate regression in linear regression tutorial

### ISSUE THREAD

**Issue by awellis** [TuringLang/Turing.jl#1143]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/5_LinearRegression.md

In the section `comparing to OLS regression` you use the term multivariate regression. Aren't you predicting a single outcome variable?

**Comment by cpfiffer** [comment]
Yes, because that is the definition of multivariate linear regression, at least in my literature. Economics has many idiosyncracies. We commonly refer to a regression with more than one independent variable and an intercept as multivariate regressions. 

You are welcome to submit a PR to change this in [TuringTutorials](https://github.com/TuringLang/TuringTutorials/blob/master/5_LinearRegression.ipynb).

**Comment by trappmartin** [comment]
Just to clarify. 

In statistics, multivariate regression refers to regression with multiple dependent variables (output), while multiple regression refers to regression with multiple independent variables (covariates, inputs).

It might be used incorrectly in the tutorial. Feel free to submit a PR to fix it.

Thanks!

**Comment by awellis** [comment]
Ah, I see. Where I'm coming from, that is usually referred to as multiple regression, with multivariate regression referring to a model with multiple outcome variables.

**Comment by trappmartin** [comment]
Yes, that's what I wrote. :)

**Comment by awellis** [comment]
yeah, sorry, didn't see that you had replied.
