### ISSUE TITLE
MethodError: no method matching Preconditioner

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/Turing.jl#1219]
After updating to AdvancedHMC v0.2.23, Turing now produces a method error for Preconditioner. Here is a MWE:

```
using Turing, Distributions, Random

Random.seed!(80214)

y = rand(Normal(0, 1), 30)

@model model(y) = begin  
    μ ~ Normal(0, 1)
    y .~ Normal(μ, 1)
end

psample(model(y), NUTS(1000,.65), 2000, 4)
```

Version:

```
st Turing
Status `~/.julia/environments/v1.4/Project.toml`
  [fce5fe82] Turing v0.10.1 ⚲
```

```
(@v1.4) pkg> st AdvancedHMC
Status `~/.julia/environments/v1.4/Project.toml`
  [0bf59076] AdvancedHMC v0.2.23

```

**Comment by devmotion** [comment]
The problem is that AdvancedHMC 0.2.22 is a breaking release but was not declared as being non-breaking (see, e.g., the difference between 0.2.21 and 0.2.22: https://github.com/TuringLang/AdvancedHMC.jl/compare/v0.2.21...v0.2.22).

The master branch of Turing is already updated to be compatible with AdvancedHMC 0.2.22, so IMO currently there are two options until a new version of Turing is released: either you use the Turing master branch or you downgrade AdvancedHMC to 0.2.21.

**Comment by itsdfish** [comment]
Sorry about that. Just before you responded, I realized that the master branch was updated and I began testing it locally. Everything looks good on my end.

**Comment by xukai92** [comment]
Sorry for this confusion. I didn't handle deprecation correctly in the recent release of AHMC. A PR is in progress to fix things.

**Comment by itsdfish** [comment]
No problem! It's easy to miss something with so many moving parts.
