### ISSUE TITLE
Unexpected domain error with Poisson model

### ISSUE THREAD

**Issue by ElOceanografo** [TuringLang/Turing.jl#1222]
Discovered this trying to fit a Poisson model where the rate parameter is occasionally 0.  The model is:
```julia
using Turing, Distributions, Random
Random.seed!(1)
x = [1, 3, 2, 5, 19, 3]
p = 0.31
y = rand.(Poisson.(p .* x))

@model poissonmodel(y, x) = begin
    p ~ Beta(1, 1)
    for i in 1:length(y)
        y[i] ~ Poisson(p * x[i])
    end
end

sample(poissonmodel(y, x), HMC(0.1, 5), 1000)
```
The above runs fine, however if there are any zeros in the `x` data, I get `ArgumentError: Poisson: the condition λ >= zero(λ) is not satisfied.`, even though ` λ` should never be less than 0:
```julia
sample(poissonmodel([0; y], [0; x]), HMC(0.1, 5), 1000) # errors
```
The model runs if I add `eps()` to the x-vector, or if I change the sampler to `MH()`, so I'm thinking this might be a floating-point problem appearing through automatic differentiation somehow?

**Comment by devmotion** [comment]
Have you tried using `p ~ Uniform()`? Maybe that's numerically more stable.

**Comment by ElOceanografo** [comment]
Just tried it, and I get the same error...

**Comment by devmotion** [comment]
Can you try
```julia
@model poissonmodel(y, x) = begin
    p ~ Beta(1, 1)
    if !isfinite(p)
        @logpdf() = -Inf
        return
    end
    for i in 1:length(y)
        y[i] ~ Poisson(p * x[i])
    end
end
```
(possibly also with `p ~ Uniform()`)?

**Comment by ElOceanografo** [comment]
That runs, but spits out a ton of "Warning: the current proposal will be rejected due to numerical errors" messages, and the samples never move from the initial value (i.e. plotting the chain shows a flat line).

**Comment by ElOceanografo** [comment]
I get the Same result for `p ~ Uniform()` and `p ~ Beta(1,1)`.

**Comment by devmotion** [comment]
Hmm, yes I guess it's due to the fact that the gradient is not defined if the counts and rate are both zero (`x` and `v` in the implementation), as you can see in https://github.com/TuringLang/DistributionsAD.jl/blob/e0f0d13f3112e7b354c22a1c373eddba361b6479/src/univariate.jl#L241-L256, since then `x/v` is `NaN`. That seems to be problematic for all AD backends.

**Comment by ElOceanografo** [comment]
I see.  Would it make sense to hard-code in a special case for when `x` and `v` are zero?  I believe the limit of the derivative of the logpdf as `v` -> 0 is -1.  Or just add `eps()` as in my hack above?

**Comment by devmotion** [comment]
Maybe I'm wrong, but I don't see how the derivative should be defined for x, v -> 0. I'm wondering why you include the values with `x[i] = 0` and `y[i] = 0` at all; in this case the Poisson distribution just collapses to a Dirac distribution at 0, regardless of `p`, and hence `y[i] = 0` is the only possible value. Since that's independent of `p`, that doesn't seem to be useful for inferring the posterior distribution of `p`? So maybe the cleanest solution would be to exclude these data pairs?

**Comment by ElOceanografo** [comment]
I ran into this issue building a state-space model where the observations are Poisson distributed, with the rate proportional to a dynamic latent state that can be zero-valued.  So in the non-MWE case, I can't eliminate the zeros beforehand. (I guess I could put a conditional `if x == 0` statement in my model, though that wouldn't have helped me debug it before I figured out what was going on.)

While I agree that the zero values aren't providing any information about `p`, and that the gradient isn't defined when `λ == 0`, the logpdf itself *is* defined.  Even if it's a (literal) corner case, from my user's perspective I guess I see it as a computational issue in the algorithm that generates samples, rather than a problem with the model specification itself.  Do you think there's a way the sampler could handle this more gracefully than throwing an error?

**Comment by devmotion** [comment]
Hmm I'm not sure, I rather see it as a mathematical issue than a computational one - the problem does not arise due to floating point errors or other computational limitations but since theoretically the gradient is not defined for data pairs `i` with `x[i] = 0.0` and `y[i] = 0`. So IMO gradient-based inference methods are doomed to fail (and supposed to fail) in this case, and if you want to keep the data and the model they are not the right inference method.

As you say, one way around this would be to check if `iszero(x[i])` if you can't eliminate the zeros. It also doesn't affect the total logpdf that you get from your model (and which Turing computes internally every time you sample from your model) since for these cases it is zero anyways. So that seems like a reasonable approach to me.
