### ISSUE TITLE
Make Gibbs components extensible (somewhat RFC...)

### ISSUE THREAD

**Issue by phipsgabler** [TuringLang/Turing.jl#1306]
We have discussed about this somewhere before... currently, anything you want to use in `Gibbs` has to be a subtype of

```julia
const GibbsComponent = Union{Hamiltonian,MH,ESS,PG,GibbsConditional}
```

so you can't just implement a compatible sampler in a separate package (which is what I would like to do these days). 

@devmotion mentioned that we should use some kind of trait, but then of course we can't have

```julia
struct Gibbs{space, A<:Tuple{Vararg{GibbsComponent}}}
```

anymore (or maybe only with some heavy trait dispatch machinery that we'd like to avoid).

I'd really like to write a quick fix for this now, but of course having a permanent improvement would be cool.

So, what about (re)introducing `gibbs_step` as [here](https://github.com/TuringLang/Turing.jl/pull/1275/commits/e9f95138fe441c32fa5863978d10f4c31fb64cab), but with the implementation

```julia
struct IsGibbs{S} end

isgibbs(::Type{S}) where {S<:Hamiltoniam} = IsGibbs{S}
# etc. for other samplers

gibbs_step!(rng::AbstractRNG, model::Model, spl::S, N, transition; kwargs...) where {S<:Sampler} = 
    gibbs_step!(isgibbs(S), rng, model, spl, N, transition; kwargs)

function gibbs_step!(
    ::IsGibbs{S},
    rng::AbstractRNG,
    model::Model,
    spl::S,
    N,
    transition;
    kwargs...) where {S<:Sampler}

    return AbstractMCMC.step!(rng, model, spl, N, transition; kwargs...)
end
```

Just a hand-written Holy trait -- I hope I got that right.  

Maybe with a macro `@allowgibbs MySampler` expanding to `DynamicPPL.isgibbs(::Type{S}) where {S<:MySampler} = IsGibbs{S}`.

**Comment by devmotion** [comment]
If you want to allow arbitrary user-defined Gibbs components, isn't it sufficient to just add DynamicPPL.isgibbs(sampler) = false, drop the type restriction, and add an inner constructor that checks if the sampler supports Gibbs sampling? IMO we don't need the type restriction if we check it in the inner constructor.

The aim of the `gibbs_step!` suggestion is just to separate the Gibbs handling more clearly from regular steps, since currently everything is mixed together in a single implementation of `step!` which is quite confusing IMO. But it is not needed if you want to support custom Gibbs samplers - with the current setup you would just have to put everything inside of a single `step!`.

**Comment by phipsgabler** [comment]
Right, we don't actually use the trait for function dispatch.  I'll have a PR ready today.
