### ISSUE TITLE
AssertionError: all(getargnames(model)) do arg

### ISSUE THREAD

**Issue by orangebacked** [TuringLang/Turing.jl#1404]
Dear Turing devs,

I'm trying to get the loglikelihoods the posterior distribution of my model. I'm following the guide you published at your website; however, I keep getting this error:

`AssertionError: all(getargnames(model)) do arg`

The  model, and the subsequent code, is the following:

@model logistic_regression(x, y, n, σ) = begin
    # priors
    intercept ~ Normal(0, σ)
    x₁ ~ Normal(0, σ)
    x₂ ~ Normal(0, σ)
    x₃ ~ Normal(0, σ)
    x₄ ~ Normal(0, σ)
    rightmultiplication = [intercept, x₁, x₂, x₃, x₄]

    N = [1 for x in 1:n]
    v =  hcat(N,x)
    vₓ = v*rightmultiplication
    # likelihood
    for (i, row) in enumerate(eachrow(vₓ))
        y[i] ~ Bernoulli(logistic(sum(row)))
    end
end;

chns_2 = sample(logistic_regression(trainₚ_normalized , train_label, n, 1), NUTS(), 100, save_state=true)

logprob"y = 1.0 | chain = chns_2"

Thank you!

**Comment by devmotion** [comment]
The problem is that you do not provide all arguments of your model (or alternatively define default arguments). The chain only saves the model and the samples of intercept, x₁, x₂, x₃, and x₄, hence you have to state x, y, n, and σ in your logprob evaluation. Something like `logprob"y = 1 | chain = chns_2, x = rand(1, 4), n = 1, σ = 1"` or also `logprob"y = train_label | chain = chns_2, x = trainp_normalized, n = n, σ = 1"` should work (BTW it seems `n` can be deduced from `x` or `y`, so you could remove it from the arguments).

**Comment by devmotion** [comment]
BTW there exists an issue for the cryptic error message: https://github.com/TuringLang/DynamicPPL.jl/issues/135

**Comment by orangebacked** [comment]
Great, thanks!

**Comment by trappmartin** [comment]
Can this be closed?

**Comment by trappmartin** [comment]
Can this be closed?
