### ISSUE TITLE
Feature request: Retrieve model name from model

### ISSUE THREAD

**Issue by goedman** [TuringLang/Turing.jl#1429]
E.g. in below example can I recover “m4_2” from m4_2t?
```
@model m4_2(x, y) = begin
    #priors
    alpha ~ Normal(178.0, 100.0)
    beta ~ Normal(0.0, 10.0)
    s ~ Uniform(0, 50)
    #model
    mu = alpha .+ beta*x
    y .~ Normal.(mu, s)
end
# Draw the samples
m4_2t = m4_2(x, y)
chns = sample(m4_2t, NUTS(0.65), 1000)
```

**Comment by devmotion** [comment]
No, AFAIK this is not possible. However, you can, e.g., retrieve a model with modified arguments, so I'm wondering what your use case is. Do you actually need the name `m4_2` here? Or is the main objective to call `m4_2`? BTW (since it changed recently) `m4_2` is just a regular Julia function (that creates the model) with the same function signature as defined by the user (the Turing `@model` doesn't modify it in any way).

**Comment by goedman** [comment]
Hi David, thanks for your response. I am really looking for the name (string) "m4_2" in my use case when plotting the parameters of several models, e.g. as in https://github.com/StatisticalRethinkingJulia/StatisticalRethinking.jl/blob/master/scripts/05/Fig-12b.png.

**Comment by devmotion** [comment]
I see. I implemented this feature in https://github.com/TuringLang/DynamicPPL.jl/pull/175.

**Comment by goedman** [comment]
Thanks David, super!

On the 2nd part of your response ("regular Julia function"), is there a difference if I use (added the word `function`):
```
@model function m4_2(x, y) = begin
    #priors
    alpha ~ Normal(178.0, 100.0)
    beta ~ Normal(0.0, 10.0)
    s ~ Uniform(0, 50)
    #model
    mu = alpha .+ beta*x
    y .~ Normal.(mu, s)
end
```
or is the old way equivalent?

**Comment by torfjelde** [comment]
If you add `function`, then you need to remove `= begin`. In julia you can either write a function as
```julia
function f(x)
end
```
or

```julia
f(x) = begin
end
```
And the `@model` macro simply wraps a function, hence you can use either of the above:)

**Comment by torfjelde** [comment]
Though

```julia
function f(x) = begin
end
```
is not valid.

**Comment by devmotion** [comment]
They are both equivalent, in the same way as
```julia
f(x, y) = begin
    x + y
end
```
and
```julia
function f(x, y)
    x + y
end
```
are equivalent.

But note that you have to remove the `= begin` part, i.e., you should write
```julia
@model function m4_2(x, y)
    #priors
    alpha ~ Normal(178.0, 100.0)
    beta ~ Normal(0.0, 10.0)
    s ~ Uniform(0, 50)
    #model
    mu = alpha .+ beta*x
    y .~ Normal.(mu, s)
end
```

**Comment by devmotion** [comment]
However, it gets a bit more interesting with keyword arguments. In previous Turing (or rather DynamicPPL) versions the function signature was parsed in a special way by `@model`, and hence, e.g., it was not possible to use keyword arguments (and type annotations were also modified in some cases). This is not the case anymore, you can just use the regular Julia syntax now (and e.g. use keyword arguments and default positional arguments in the standard way).

**Comment by goedman** [comment]
Of course, that makes sense! Thanks a lot!

**Comment by devmotion** [comment]
I'll close this issue since the feature was added to DynamicPPL. As soon as https://github.com/JuliaRegistries/General/pull/22539 is merged into the registry, an update with `Pkg` should give you the latest version which supports to retrieve the "name" of a model with `nameof`. E.g., in the initial example you should be able to get the name `:m4_2` with
```julia
nameof(m4_2t)
```
