### ISSUE TITLE
How do I contribute a tutorial?

### ISSUE THREAD

**Issue by caseykneale** [TuringLang/Turing.jl#1442]
Hi Turing.jl crowd,

I have a tutorial I'd like to contribute, but I cannot access the /src_tutorials/ directory? What I could do is put it on one of my repositories and put a link in this issue for your reviewal?

**Comment by devmotion** [comment]
The tutorials are not part of the Turing.jl repo but located in [TuringTutorials](https://github.com/TuringLang/TuringTutorials). Currently, most tutorials are outdated but there is some [ongoing work](https://github.com/TuringLang/TuringTutorials/issues/86) to update them and to use the jmd format instead of Jupyter notebooks.

**Comment by caseykneale** [comment]
Haven't heard of *.jmd I assume that's Pluto? I think I'll install Jupyter and jupyify what I have, might take a little while though.

**Comment by cpfiffer** [comment]
`.jmd` is from [Weave.jl](https://github.com/JunoLab/Weave.jl), which is what we're moving over to instead of Jupyter notebooks. I think Weave has utilities to convert Jupyter notebooks to `.jmd` files.
