### ISSUE TITLE
"Domain-specific object" syndrome

### ISSUE THREAD

**Issue by extradosages** [TuringLang/Turing.jl#1458]
Turing does a fantastic job or bringing together functionality and information from disparate sources, but it's beginning to suffer from what I call "domain-specific object" syndrome. This is the unfortunate state of forgoing passing data to and from a system in it's more primitive forms, and instead wrapping them in lightweight containers. Python suffers from this immensely, both because it lacks nice primitive data structures and because of the necessity of OOP in every facet of programming.

Mode estimates are a good example:
```
"""
    ModeResult{
        V<:NamedArrays.NamedArray, 
        M<:NamedArrays.NamedArray, 
        O<:Optim.MultivariateOptimizationResults, 
        S<:NamedArrays.NamedArray
    }
A wrapper struct to store various results from a MAP or MLE estimation.
"""
struct ModeResult{
    V<:NamedArrays.NamedArray, 
    O<:Optim.MultivariateOptimizationResults,
    M<:OptimLogDensity
} <: StatsBase.StatisticalModel
    "A vector with the resulting point estimates."
    values :: V
    "The stored Optim.jl results."
    optim_result :: O
    "The final log likelihood or log joint, depending on whether `MAP` or `MLE` was run."
    lp :: Float64
    "The evaluation function used to calculate the output."
    f :: M
end
```
This really only needs to store a dict of values. There are no docs on how to interact with a mode result, the following screenshot being the only examples of an API into this struct in all of the documentation:
![Screen Shot 2020-11-16 at 7 05 30 PM](https://user-images.githubusercontent.com/22087689/99322837-d1ed3800-283e-11eb-862e-0d294d9b9849.png)

The `hpd` function in MCMC chains returns a `ChainDataFrame`. I had no idea how to use this. It only needed to return a `Dict{Symbol, Tuple}`.

I'll edit in more examples as I come across them.

It would be fair enough to update the documentation, but why not just simplify the interface?

**Comment by jkbest2** [comment]
Are you proposing that `ModeResult` should be a `Dict`? I don't see any advantage, and a number of disadvantages. You can still get individual fields of the struct, e.g. `mr.values` to get values from `mr`, and each field can be concretely typed (unlike a `Dict`). I'm sure that your MAP as initial value example is how it works "under the hood", but it also allows for extending with other kinds of initial value objects (maybe a `NamedArray` of `Distributions` to sample from for the intial values).

**Comment by cpfiffer** [comment]
The reason it doesn't return just a `Dict` (in addition to @jkbest2's comments) is that we can efficiently use it for other things like calculating Hessians, standard errors, etc. 

As to your other issue:

> The `hpd` function in MCMC chains returns a `ChainDataFrame`. I had no idea how to use this. It only needed to return a `Dict{Symbol, Tuple}`.

We'd be happy to help point out how to use this. Not knowing how to use something is not really a good motivation for removing a feature set.

**Comment by devmotion** [comment]
I just want to add something regarding ChainDataFrame. Previously we used a regular DataFrame but the dependency on DataFrames increased the package loading and compilation time and the number of implicit dependencies significantly. By using a custom struct instead the dependency on DataFrames could be dropped. Importantly, in addition to some basic functionality for printing and indexing, ChainDataFrame implements the Tables interface, and hence can be used by any package that handles Tables - such as DataFrames, which allows you to construct a DataFrame by just calling `DataFrame(table)`. The documentation of MCMCChains could and should be improved but I don't think that per se it is bad that ChainDataFrame exists - it is common that Julia packages define their own table-like structs, since this allows to customize the display and eg. indexing without type piracy and nevertheless can be connected to the ecosystem by implementing the Tables interface. For instance, in recent version CSV.jl defines only its custom structs and dropped the dependency on DataFrames.

**Comment by extradosages** [comment]
Oh I can clarify that I don't think it's "bad" that any of these objects exist-- with the present state of documentation there is just a barrier to entry that's been introduced by all these little domains that people have to work with.

I opened this issue a bit in haste and frustration after spending a good fifteen minute trying to extract information from a `ModeResult`. How about I take this weekend to see what concrete help I can offer? Whether that be proposed improvements, or just documentation. Probably in `MCMCChains`, where it seems things are most dire.

**Comment by cpfiffer** [comment]
Yeah, MCMCChains is definitely the most lacking.
