### ISSUE TITLE
About Profiling Memory Allocation in Turing

### ISSUE THREAD

**Issue by yushang-lai** [TuringLang/Turing.jl#1480]
Hi!

 Is there a way to profile the memory allocation for each inference variable inside the @model function while using Turing? I tried to profile the sample(bayes_ode(u,du,p,t),NUTS(0.65),10) function by using Profile.jl. However, it seems the lines inside @model 
 do not count for memory allocation.

Thanks a lot in advance!
Best.

**Comment by devmotion** [comment]
I have never tried to profile Turing models with Profile.jl but it should just work. The @model macro just modifies the function body of the model function a bit but `bayes_ode` is really just a regular Julia function with the function signature that you defined. However, I guess the output of Profile.jl might be a bit difficult to interpret since the model function ends up being an anonymous function that is saved (together with the data) in the `Model` struct that is returned by `bayes_ode`.

Or put differently with an "example": The basic principle of the `@model` macro is to rewrite
```julia
@model function f(args...; kwargs...)
    body...
end
```
to
```julia
function f(args...; kwargs...)
   evaluator##1 =
       (_rng::AbstractRNG, _model::DynamicPPL.Model, _varinfo::DynamicPPL.AbstractVarInfo, _sampler::AbstractMCMC.AbstractSampler, _context::DynamicPPL.AbstractContext, args..., names_of_kwargs...) -> begin
        body...
    end
    return DynamicPPL.Model(name_of_f, evaluator##1, namedtuple_of_args_and_kwargs, namedtuple_of_default_args_and_kwargs)
end
```
