### ISSUE TITLE
Pass args... to DynamicNUTS

### ISSUE THREAD

**Issue by ClaudMor** [TuringLang/Turing.jl#1505]
Hello,

From the [documentation of DynamicNUTS](https://turing.ml/dev/docs/using-turing/dynamichmc), which if I understood correctly should be a wrapper to [DynamicHMC.jl](http://tamaspapp.eu/DynamicHMC.jl/stable/interface/), I'm not able to understand how to pass to DynamicHMC arguments like `initialization` and `warmup_stages`, that you may find in the DynamicHMC documentation above.

Thanks in advance

**Comment by devmotion** [comment]
DynamicHMC are not supported currently and hence not listed in the documentation.

**Comment by devmotion** [comment]
The implementation does not wrap `DynamicHMC.mcmc_with_warmup` but instead wraps the unofficial internal iteration interface with AbstractMCMC. This enables some features that are not supported by DynamicHMC, such as thinning, discarding initial samples, and parallel sampling instead.

**Comment by devmotion** [comment]
In general, `NUTS` is better supported and has more options.

**Comment by claudio20497** [comment]
Thank you very much.

**Comment by claudio20497** [comment]
Hello @devmotion , 

is there any way we can pass initial parameter values to `NUTS` or other samplers?

I see that there is a `θ` argument to [this `sample` method](https://turing.ml/dev/docs/library/advancedhmc/), but I'm not sure that it is the one that gets called when we do things like:

```julia
chain2 = sample(model2, NUTS(.45), MCMCThreads(), 5000, 3, progress=false)
```

( example taken from the [docs](https://turing.ml/dev/tutorials/10-bayesiandiffeq/) ).

**Comment by devmotion** [comment]
AdvancedHMC does not use AbstractMCMC (yet), so it does implement `sample` in a different way and with different options than Turing and other AbstractMCMC-dependent packages, and in particular it can't benefit from the AbstractMCMC defaults such as parallel sampling and the DynamicPPL defaults for parameter initialization. You can specify initial values of a Turing model with `init_params` (the documentation is not correct here) but there are some caveats and unfortunately I noticed a bug when running a simple example. It is fixed by https://github.com/TuringLang/DynamicPPL.jl/pull/210, you can have a look at the PR for some examples as well. The main limitation of `init_params` currently (which should be changed) is that you have to specify values for *all* parameters in the order they appear in the Turing model as a collection of arrays and/or scalars. If some parameters should not be initialized, this can indicated by a `missing` value.
