### ISSUE TITLE
New AD Yota.jl

### ISSUE THREAD

**Issue by storopoli** [TuringLang/Turing.jl#1553]
I saw that there is a new Autodiff called [`Yota.jl`](https://github.com/dfdx/Yota.jl)

On [Julia's Discourse](https://discourse.julialang.org/t/where-does-julia-ecosystem-provide-the-greatest-speedup-and-where-does-it-lag-the-most-behind-compared-to-e-g-python/56565/18?u=storopoli) someone mentioned:
> Yota.jl is faster than Zygote.jl and Jax.

Have you guys experimented with it?

**Comment by cpfiffer** [comment]
No, I don't think anyone's tooled around with it yet. In general I think we're taking adding ADs carefully since there's a lot of them out there of varying degrees of stability.

**Comment by storopoli** [comment]
Ok, this was just a FYI. If you want, you can close it. :)

**Comment by cpfiffer** [comment]
I'll defer closing it to one of the more AD-focused people like @mohamed82008 -- should we consider Yota.jl at the moment or wait until it's more stable?

**Comment by devmotion** [comment]
Yota is not really new, it exists since 2019. Apart from that I can't provide any useful comment here, I've never used it - e.g., I don't know how stable and mature it is. It seems to support ChainRulesCore, so ChainRules support in DistributionsAD would be sufficient and no Yota-specific implmentations would be required. I assume the only missing part would be a logp gradient implementation in Turing - it would be nice to generalize this part of the API in a way that would make it easier to support other AD backends.

**Comment by mohamed82008** [comment]
When I tried it 1-2 years ago, it wasn't stable enough. If you believe it is stable now, please follow the code in https://github.com/TuringLang/Turing.jl/blob/master/src/core/ad.jl to see how to add a new AD backend. Then run a few tests.

**Comment by yebai** [comment]
`ReverseDiff` is probably the best option for a long time - we plan to further improve ReverseDiff to handle dynamic models more efficiently.
