### ISSUE TITLE
Mention Zulip channel in the README?

### ISSUE THREAD

**Issue by juliohm** [TuringLang/Turing.jl#1596]
I noticed that Turing.jl has a large community in Zulip already. Would it make sense to add it to the README?

**Comment by devmotion** [comment]
I guess it could be useful if it is active and also used by some of the developers. I don't know if this is the case? I only use Zulip occasionally since I have to use Slack for work anyway and am already busy enough with Github and Slack. And both the Slack channel and the Github discussion page are mentioned in the README, so probably one should not offer too many alternatives if they are not actively monitored.

I am not very active on discourse either but I know that e.g. @torfjelde and @cpfiffer answer questions there - maybe one should mention it in the README instead? In general, maybe one should advertise it more and direct users there from Slack, similar to e.g. the push of the Makie developers?

**Comment by juliohm** [comment]
I asked about Zulip because Slack erases these valuable answers from developers. The Turing channel in Zulip currently has 122 members and all discussions are archived.

Feel free to close the issue if you don't feel that Zulip should be mentioned. I will ask my question in Discourse as well so that the answers are useful to future users.

**Comment by devmotion** [comment]
I completely agree, I am not a fan or advocate of Slack, my main concern is just that we should not advertise something that is not used actively by the developers.

**Comment by cpfiffer** [comment]
Yeah, I feel like if we were going to add another comms tool, the Discourse is the better candidate. Stuff there is searchable and a little more accessible than either Zulip or Slack. 

FWIW I am sort of on Zulip but I don't tend to actively review it like I do with Slack. I also get emails for various relevant Discourse threads, which I think is why I tend to be more active there.

**Comment by juliohm** [comment]
I feel that any project in Julia should target Discourse for open discussion with more delayed response and Zulip for instantaneous chat and support. Discourse is already mentioned in the README. What I feel is suboptimal is Slack. The lack of archival is simply a waste of human resources and knowledge. Everyone comes and can't find answers to previously asked questions.

I will close the issue for now, and will let the devs decide which platform is best for the project.

**Comment by torfjelde** [comment]
I try to be on Zulip these days btw! Had to drop it a while back because I didn't have enough RAM to run all these clients at the same time, but now I do :+1:
