### ISSUE TITLE
Question: model in tutorial doesn't wor

### ISSUE THREAD

**Issue by BrettKnoss** [TuringLang/Turing.jl#1600]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/0_Introduction.md

```
@model coinflip(y) = begin
    
    # Our prior belief about the probability of heads in a coin.
    p ~ Beta(1, 1)
    
    # The number of observations.
    N = length(y)
    for n in 1:N
        # Heads or tails of a coin are drawn from a Bernoulli distribution.
        y[n] ~ Bernoulli(p)
    end
end
iterations = 1000
ϵ = 0.05
τ = 10
chain = sample(coinflip(data), HMC(ϵ, τ), iterations, progress=false);
```
gives the following error.
```
[ Info:  Assume - `p` is a parameter
[ Info:  Observe - `y` is an observation
ERROR: MethodError: no method matching sample(::typeof(coinflip_model), ::HMC{Union{}}, ::Int64; progress=false)
Closest candidates are:
  sample(::Function, ::T; chunk_size, save_state, resume_from, reuse_spl_n, adapt_conf) where T<:Turing.Hamiltonian at /home/brett/.julia/packages/Turing/YnwiD/src/samplers/hmc.jl:97 got unsupported keyword argument "progress"
  sample(::AbstractArray, ::AbstractWeights, ::Integer; replace, ordered) at /home/brett/.julia/packages/StatsBase/548SN/src/sampling.jl:788 got unsupported keyword argument "progress"
  sample(::Function, ::Gibbs; save_state, resume_from, reuse_spl_n) at /home/brett/.julia/packages/Turing/YnwiD/src/samplers/gibbs.jl:51 got unsupported keyword argument "progress"
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[39]:1
```

**Comment by devmotion** [comment]
The example works for me with the latest Turing version (0.15.18) and Julia 1.6.1. Maybe you use an old version of Turing?

**Comment by BrettKnoss** [comment]
Ok. I just added Turing and thd rest of these packages. How do I ensure I have the newest version, is that where I use build in the package manager?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by devmotion** [comment]
Usually just running
```julia
julia> ] up
```
in the Julia REPL should ensure that you use the most recent versions. You can check the version of the packages that you have installed explicitly with
```julia
julia> ] st
```
and of all installed packages (including the dependencies that were installed automatically) with
```julia
julia> ] st --manifest
```
If you install other packages apart from Turing as well (e.g., if you install all packages in the default environment) it can happen that another dependency holds back Turing and not the latest version of Turing is installed. You can try to install the latest version of Turing explicitly with
```julia
julia> ] add Turing@0.15.19
```
and in case this is not possible due to some other package it should explain which package holds it back. Generally, I recommend working with [project environments](https://pkgdocs.julialang.org/v1/environments/) since it simplifies the package management (less dependencies that can potentially interfere) and helps to make the package state reproducible.

**Comment by BrettKnoss** [comment]
I'm told that I'm restricted to version 0.5.0-0.15.18

I currently have Turing 0.5.1

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by devmotion** [comment]
This is a very ancient version of Turing, I am not surprised that the example does not work with it. What is the output of
```julia
julia> ] add Turing@0.15.18
```
(probably you have to run `] up` to update the registry before version 0.15.19 is available for you)?

**Comment by BrettKnoss** [comment]
I fixed it but now there's a problem with ids. Can we go to a chat that's not a forum?

Sent from ProtonMail mobile

-------- Original Message --------
