### ISSUE TITLE
`pointwise_loglikelihoods` ambiguous/silently returns incorrect values 

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/Turing.jl#1666]
The `pointwise_loglikelihoods` method currently is ambiguous, and can return incorrect values that easily go unnoticed by users. The main problem is that statements of this form are ambiguous:
```
y .~ Normal(0, 1)
```
This method could mean one of two things:
1. `y` is a vector of features from a single observation, which are assumed to be independent. 
2. `y` is a vector of observations, each of a single feature.

A similar problem occurs with `for` loops. Either of these can result in incorrect values for functions like WAIC or PSIS-LOO when using ArviZ or ParetoSmooth.jl. While both packages include warnings in their docstrings against using broadcasting for independent observations, these warnings are easy to miss, and the "fix" (using `for` loops instead of broadcasting) requires users to give up performance or use potentially unnatural syntax. (I naturally gravitate towards `.~` for observations, for instance, and it took me a while to notice a bug of this kind when trying to use ArviZ.jl.)

**Comment by ParadaCarleton** [comment]
My own suggestion -- perhaps we can take advantage of Tables.jl for this? The overwhelming majority of data analysis in Julia will be done using some data structure that implements the table interface, and rows of tables usually represent distinct observations.

**Comment by AntoineAsselin78** [comment]
@ParadaCarleton I am also having problem with `pointwise_loglikelihoods`. I have two issues with `?pointwise_loglikelihoods`

> Unfortunately, just by looking at the latter statement, it's
  impossible to tell whether or not this is one single observation
  which is n dimensional OR if we have multiple 1-dimensional
  observations. Therefore, loglikelihoods will only work with the
  first example.

# First issue

Not being able to use dot broadcasting. This is what I have been doing, firstly, I sample model with dot broadcasting for performance.

```jl
using DynamicPPL, Turing

@model function demo(x,y)
    s ~ InverseGamma(2,3)
    a ~ Normal(0,1)
    b ~ Normal(0,1)
    mu = a .+ b * x
    y .~ Normal.(mu, s)
end
model = demo(randn(3), randn(3))
chain = sample(model, MH(), 10)
```

I then change model to `for` loop just to use `pointwise_loglikelihoods`

```jl
@model function demo(x,y)
    s ~ InverseGamma(2,3)
    a ~ Normal(0,1)
    b ~ Normal(0,1)
    mu = a .+ b * x
    for i in eachindex(y)
        y[i] ~ Normal(mu[i], s)
    end
end
model = demo(randn(3), randn(3))
pointwise_loglikelihoods(model, chain)
```

Then change it back

```jl
@model function demo(x,y)
    s ~ InverseGamma(2,3)
    a ~ Normal(0,1)
    b ~ Normal(0,1)
    mu = a .+ b * x
    y .~ Normal.(mu, s)
end
model = demo(randn(3), randn(3))
```

# Second issue

How do I get the pointwise loglikelihoods for multivariate distributions like `MvNormal`? I get wrong results due to it being treated as _one single observation which is n dimensional_

```jl
@model function multivariate(y)
    k ~ InverseWishart(2, [1 0; 0 1])
    mu ~ filldist(Normal(0,1),2)
    y ~ MvNormal(mu, k)
end
model2 = multivariate(randn(2))
chain2 = sample(model2, MH(), 10)
pointwise_loglikelihoods(model2, chain2)
# Wrong 
```

# Potential fix

Since _multiple 1-dimensional observations_ is the most common use case shouldn't this be the default? For obtaining `pointwise_loglikelihoods` with _one single observation which is n dimensional_ a keyword argument could be introduced for those scenarios? `pointwise_loglikelihoods(model, chain, single_observation = true)`. This could solve both issues?

**Comment by torfjelde** [comment]
I agree that when computing the pointwise loglikelihood `.~` should treat LHS as a collection of independent variables rather than a single multivariate observation because:
1. this seems to be what people expect, i.e. is most intuitive,
2. treating it as a single multivariate can be done either by the use of `filldist` or `arraydist`, hence if this is the user's intention it's easy to change.

I've opened a PR to address this issue, so should be fixed very soon:)

> How do I get the pointwise loglikelihoods for multivariate distributions like MvNormal? 

Unfortunately this is not something we'll likely address in the near future. For a general `MultivariateDistribution` this question just cannot be answered + IMO it does go against the semantic meaning of `MvNormal`: it represents a single multivariate random variable, not a collection of such. Hence if you want a collection of independent observations, then you should use `.~`. Note that both the LHS and RHS of `.~` can be arrays, e.g. `[1.0, 2.0] .~ [Normal(), Normal()]` also works.

**Comment by AntoineAsselin78** [comment]
Thank you @torfjelde for PR. I am looking forward to it. I still have question w.r.t. `MultivariateDistribution`

> > How do I get the pointwise loglikelihoods for multivariate distributions like MvNormal?
> 
> Unfortunately this is not something we'll likely address in the near future. For a general `MultivariateDistribution` this question just cannot be answered + IMO it does go against the semantic meaning of `MvNormal`: it represents a single multivariate random variable, not a collection of such. Hence if you want a collection of independent observations, then you should use `.~`. Note that both the LHS and RHS of `.~` can be arrays, e.g. `[1.0, 2.0] .~ [Normal(), Normal()]` also works.

I have a project and the purpose is to model Gaussian Process. A dummy example

```jl
using LinearAlgebra
using Turing
using Distances

x = randn(10)
y = cos.(x)

distance = pairwise(Euclidean(), x)
exponentialKern(distance, lengthScale) = exp(-distance / lengthScale)

@model function gaussianProcess1(distance, y)
    lengthScale ~ Exponential(0.5)
    k = exponentialKern.(distance, lengthScale) + 1e-3*I
    y ~ MvNormal(zeros(10), k)
end

model = gaussianProcess1(distance, y)
chain = sample(model, HMC(0.05, 10), 10)
pointwise_loglikelihoods(model, chain)  
# returns wrong results  
```

In such case, how should I go about getting the `pointwise_loglikelihoods`? Because I cannot use `for` loop or `dot tilde` `.~`. It is also needed by [ParetoSmooth.jl](https://github.com/ParadaCarleton) AFAIK.

**Comment by torfjelde** [comment]
What do you expect `pointwise_loglikelihoods` to compute here?

**Comment by torfjelde** [comment]
Fixed by https://github.com/TuringLang/DynamicPPL.jl/pull/281. Just make sure you're using DynamicPPL@0.12.4 or higher.
