### ISSUE TITLE
HMC of Turing and TF

### ISSUE THREAD

**Issue by raj-brown** [TuringLang/Turing.jl#1716]
Dear All-
I wrote a BNN code using Tf  Probability and Turing . The TF Probability does the job in 2 min and Turing Takes 8mins  and does not give me the good results also. Here is my Turing code and will really appreciate for your help in suggesting some pointers.

Thanks!

```using Flux
using StatsPlots
using Random
using DynamicHMC, Turing
using ReverseDiff

Turing.setprogress!(true)
Turing.setadbackend(:reversediff)

layers = [
	(50, 1, :tanh),
	(50, 50, :tanh),
	(1, 50, :σ)
]

num_params = sum([in*out+out for (out, in, _) in layers])
noise = 0.1

num = 40
x_train_1 = LinRange(-0.8, -0.2, num)
x_train_2 = LinRange(0.2, 0.8, num)
x_train = vcat(x_train_1, x_train_2)
y_train = sin.(6*x_train).^3 + noise*randn(length(x_train))

function unpack(θ::AbstractVector, layers::AbstractVector)
	index = 1
	weights = []
	biases = []
	for layer in layers
		out_dims, in_dims, _ = layer
		size = in_dims*out_dims
		last_index_w = size + index - 1
		last_index_b = last_index_w + out_dims
		push!(weights, reshape(θ[index:last_index_w], out_dims, in_dims))
		push!(biases, reshape(θ[last_index_w+1:last_index_b], out_dims))
		index = last_index_b + 1
	end
	return weights, biases
end

function nn_forward(x, θ::AbstractVector, layers::AbstractVector)
	weights, biases = unpack(θ, layers)
	nn_layers = []
	for i in eachindex(layers)
		#print(size(weights[i]))
		push!(nn_layers, Dense(weights[i], biases[i], eval(layers[i][3])))	
	end
	nn = Chain(nn_layers...)
	return nn(x)
end

@model bayes_nn(xs, ys, layers, num_params) = begin
	θ ~ MvNormal(zeros(num_params), ones(num_params))
	preds = nn_forward(xs, θ, layers)
	for i = 1:length(ys)
		ys[i] ~ Normal(preds[i], noise)
	end
end

function nn_pred_mean(x, theta, num, layers)
	mean([nn_forward(x, theta[i, :], layers)[1] for i in 1000:num])
end

function nn_pred_std(x, theta, num, layers)
	std([nn_forward(x, theta[i, :], layers)[1] for i in 1000:num])
end

burn = 3000
nsamples = 1000

# Compile

# Run


#hmc_chain = sample(bayes_nn(hcat(x_train...), y_train, layers, num_params), NUTS(nadapt, target_accept_ratio, max_depth=10), iterations)



hmc_chain = sample(bayes_nn(hcat(x_train...), y_train, layers, num_params), HMC( 0.01, 50), burn + nsamples)
post_samples = MCMCChains.group(hmc_chain, :θ).value
post_samples



num_test = 101
x_test = collect(range(-1, stop=1, length=num_test))
y_test = [nn_pred_mean([x], post_samples, length(hmc_chain), layers)[1] for x=x_test]
y_test_std = [nn_pred_std([x], post_samples, length(hmc_chain), layers)[1] for x=x_test]


y_ref = sin.(6*x_test).^3
#x_plot = vcat(x_test...)
y_test = vcat(y_test...)
y_test = vcat(y_test_std...)

scatter(x_train, y_train)
plot!(x_test, y_ref, line=(:black))
plot!(x_test, y_test, line=(:dash, :red))
plot!(x_test, y_test, fillrange=2*y_test_std, fillalpha=0.3, c=1)



#=
@model function gdemo(x, y)
	s ~ InverseGamma(2, 3)
	m ~ Normal(0, sqrt(s))
	x ~ Normal(m, sqrt(s))
	y ~ Normal(m, sqrt(s))
end

chn = sample(gdemo(1.5, 2), HMC(0.1, 5), 1000)

describe(chn)

p = plot(chn)
=#
```

**Comment by torfjelde** [comment]
> The TF Probability does the job in 2 min and Turing Takes 8mins and does not give me the good results also.

Regarding the convergence-issues, are you using the exact same samplers? I see you've commented out the `sample` using `NUTS` which makes me believe that you tried `NUTS` first but it was too slow so you went with standard `HMC` instead? If so, that explains the poor sample results.

For the performance: it's worth pointing out that we don't necessarily expect the same performance as TFP since Turing.jl is a general-purpose PPL whose main-goal is to make it _convenient_ to build complex models. In contrast, TFP generally requires much more manual labour to build the function that defines you logjoint, which in turn you can use to sample.
Now Bayesian NNs are _not_ particularly complex (at least not as a standalone with Guassian priors on the weights), i.e. they're well-suited for TFP and Turing.jl might be a bit of an "overkill" for what you're trying to achieve.

A better performance comparison is to define the logjoint:

```julia
using LinearAlgebra # gives us `I` which is preferred over `ones(...)` in `MvNormal`

function logjoint(θ)
    preds = nn_forward(xs, θ, layers)
    prior = logpdf(MvNormal(zeros(length(θ)), I), θ)
    loglikelihood = sum(logpdf.(Normal.(preds, noise), ys))
    return prior + loglikelihood
end
```

and then use `NUTS` from AdvancedHMC.jl directly (see the README for example of how to do this) to sample from this joint.

With that being said, your implementation has quite a few performance issues:
1. ReverseDiff.jl isn't compiling the tape (see: https://turing.ml/dev/docs/using-turing/autodiff). If you go with the `logjoint` approach instead, I'd also recommend checking trying out Zygote.jl.
2. You're `unpack` and `nn_forward` methods are using a bunch of non-inferrable array-types, e.g. `weights = []`, which will slow tings down (in particular when you try to compile the gradient computation). You're also using `eval` for the `layers` which is going to be quite slow (and I'd highly recommend against using `eval` like this). For building a network from the linearized parameters, I'd recommend having a look at using [`Flux.destructure`](https://fluxml.ai/Flux.jl/stable/utilities/#Flux.destructure) instead. This will simplify things + make your code faster.

**Comment by raj-brown** [comment]
@torfjelde  Thank you! I tried to run the example mentioned on AdvanedHMC.jl package [github](https://github.com/TuringLang/AdvancedHMC.jl#gradients) even that is not working.It says `NUTS{MultinomialTS, GeneralisedNoUTurn}(integrator) does not match any method`.. I will appreciate your help. Though I will raise the issue with on gitissues of AdvancedHMC. Thanks!

**Comment by torfjelde** [comment]
Is it a namespace issue, i.e. does `AdvancedHMC.NUTS` work? It definitively _should_ work because the implementation exists in AdvancedHMC.jl, so either it's because you've done both `using Turing` and `using AdvancedHMC`, which results in namespace clash since different `NUTS` types are present in these packages, _or_ you're using an old version of `AdvancedHMC`.

**Comment by raj-brown** [comment]
@torfjelde I will really appreciate if you can help me out with this. Thank you!
