### ISSUE TITLE
UndefVarError: CodeInfo not defined

### ISSUE THREAD

**Issue by andreasko** [TuringLang/Turing.jl#1756]
Hey all,

after switching Julia from 1.6.2 to 1.6.5, I experience problems when using ReverseDiff in combination with Memoization, The following MWE fails:

```julia
using Turing
using Memoization
using ReverseDiff
setadbackend(:reversediff)
Turing.setrdcache(true)


@model function demo(xs)
   s ~ InverseGamma(2, 3)
   m ~ Normal(10, √s)
   xs .~ Normal(m, √s)
end
model = demo(randn(10));
chain = sample(model, NUTS(), 10);
```

The full error message is

```
UndefVarError: CodeInfo not defined
in eval at base/boot.jl:360 
in top-level scope at test_regional.jl
in top-level scope at base/timing.jl:210 
in macro expansion at test_regional.jl:112 
in  at Turing/uMQmD/src/inference/Inference.jl:132
in #sample#1 at Turing/uMQmD/src/inference/Inference.jl:132 
in sample##kw at Turing/uMQmD/src/inference/Inference.jl:142 
in #sample#2 at Turing/uMQmD/src/inference/Inference.jl:142 
in sample##kw at Turing/uMQmD/src/inference/hmc.jl:116 
in var"#sample#40" at Turing/uMQmD/src/inference/hmc.jl:133
in  at AbstractMCMC/BPJCW/src/sample.jl:107
in var"#mcmcsample#20" at AbstractMCMC/BPJCW/src/sample.jl:114
in macro expansion at AbstractMCMC/BPJCW/src/logging.jl:8 
in macro expansion at ProgressLogging/6KXlp/src/ProgressLogging.jl:328 
in macro expansion at AbstractMCMC/BPJCW/src/sample.jl:123 
in step##kw at DynamicPPL/RcfQU/src/sampler.jl:62 
in var"#step#17" at DynamicPPL/RcfQU/src/sampler.jl:87
in  at Turing/uMQmD/src/inference/hmc.jl:153
in var"#initialstep#41" at Turing/uMQmD/src/inference/hmc.jl:167
in phasepoint at AdvancedHMC/HQHnm/src/hamiltonian.jl:153 
in phasepoint at AdvancedHMC/HQHnm/src/hamiltonian.jl:76 
in ∂H∂θ at AdvancedHMC/HQHnm/src/hamiltonian.jl:31
in ∂logπ∂θ at Turing/uMQmD/src/inference/hmc.jl:433 
in gradient_logp at Turing/uMQmD/src/core/ad.jl:83 
in gradient_logp at Turing/uMQmD/src/core/ad.jl:83 
in gradient_logp at Turing/uMQmD/src/core/compat/reversediff.jl:69 
in memoized_taperesult at Turing/uMQmD/src/core/compat/reversediff.jl:86 
in memoized_taperesult at Memoization/LiJeV/src/Memoization.jl:98
in  at base/boot.jl:571
in var"#s487#29" at base/none
in #s487#29 at Memoization/LiJeV/src/Memoization.jl:117
```

Sorry in advance if this is not related to Turing but rather to Memoization but, I can't make much sense of the error message.

Cheers!

Edit:
Here is the package list
```
Memoization v0.1.13
ReverseDiff v1.12.0
Turing v0.19.2

```

**Comment by devmotion** [comment]
Does it work without memoization?

**Comment by andreasko** [comment]
yes, when setting `Turing.setrdcache(false)` the above example works

**Comment by devmotion** [comment]
Test errors on the master branch are caused by the same error (eg https://github.com/TuringLang/Turing.jl/runs/4629430127?check_suite_focus=true#step:6:379). It seems tests pass with previous Julia versions (< 1.6.5) and is only present in Julia 1.6.5. Thus it seems one of the changes in Julia 1.6.5 broke memoization. I assume it is an upstream bug in Memoization but I don't have a non-Turing example (put away my computer for some days 🎅).

**Comment by torfjelde** [comment]
Likely the cause: https://github.com/JuliaLang/julia/compare/v1.6.4...v1.6.5#diff-6805ce4225f84b60b14f09c34f810459b8fc107b969581982d6b3c70091b934fR430-R433

Uncertain how it exactly affects Memoize.jl though.

**Comment by devmotion** [comment]
Sorry, forgot about this issue when I got hold of my computer again.

> Uncertain how it exactly affects Memoize.jl though.

I don't think it affects Memoization.jl at all - I think it's another case where the name `Core` for a module in Turing is problematic due to incorrect escaping, similar to https://github.com/simonster/Reexport.jl/pull/33#issuecomment-904570015. I assume Julia tries to resolve `Core.CodeInfo` in https://github.com/JuliaLang/julia/blob/9058264a69f9efc1af805c4473c946f87859b731/base/expr.jl#L432-L433 as `Turing.Core.CodeInfo` but of course this is not defined.

**Comment by devmotion** [comment]
It's unfortunate that this time the escaping problem is in base Julia and hence it will take much more time until a fix is available (I would assume it would be backported to 1.6 but I have no clue about the release cycle). Hence it is probably much easier and faster to rename `Turing.Core`.

**Comment by torfjelde** [comment]
Aaaah one of those again.. And yeah, I'm in the process of renaming it right now. But indeed seems like correct escaping in `@generated` fixes the issue :+1:

**Comment by devmotion** [comment]
> And yeah, I'm in the process of renaming it right now.

Ah, missed this and opened a separate PR :smile:

**Comment by devmotion** [comment]
BTW the `@generated` macro is fixed in the master branch of Julia, and the bugfix will be backported to Julia 1.6 and 1.7.
