### ISSUE TITLE
Do I understand right?

### ISSUE THREAD

**Issue by j-fu** [TuringLang/Turing.jl#1826]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/00_introduction.md

Hi, trying to learn MCMC sampling from the Turing tutorial. 

I try to understand the function `updated_belief` - in the n-th step it runs always runs through all the data from the beginning. But my (possibly wrong) understanding of Bayesian inference is that in each step, we would just add one coinflip and improve our belief by that. I also works, see this  [pluto notebook](https://gist.github.com/j-fu/fa78b371f76c0e21b6035a49aed3e4ff).

**Comment by devmotion** [comment]
It's because in the function we always update the initial prior belief (uniform distribution), and hence we have to take into account all coin flips. Alternatively, one could use the posterior obtained with n-1 coin flips as prior and update it with the nth coin flip. This would require to save the updated prior though which we don't do in the implementation.

**Comment by j-fu** [comment]
Ah ok, so your second variant is what I had in mind and implemented in the notebook. From your words I understand that this is also correct and it's up to implementation decisions what to use.
