### ISSUE TITLE
Concrete `terse` structs

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/Turing.jl#1830]
The type signatures on everything make error messages very hard to read. Should we look at `@concrete terse struct` to cut down on that?

**Comment by devmotion** [comment]
IMO ideally we should just throw better error messages for common errors. I think users shouldn't receive long and undecipherable stack traces if possible in the first place. An example of how this can be achieved is https://github.com/SciML/DiffEqBase.jl/blob/0d45bb0f6dd6ac8ce1c24981c7a164db0721eb0d/src/solve.jl#L74-L260.

**Comment by ParadaCarleton** [comment]
> IMO ideally we should just throw better error messages for common errors. I think users shouldn't receive long and undecipherable stack traces if possible in the first place. An example of how this can be achieved is https://github.com/SciML/DiffEqBase.jl/blob/0d45bb0f6dd6ac8ce1c24981c7a164db0721eb0d/src/solve.jl#L74-L260.

Oh definitely, but this is one way to make that stack trace much shorter and easier to decipher.

**Comment by devmotion** [comment]
Often the information in the stacktrace is useful for developers, so I don't think it should be hidden. It happens quite regularly that I have a, surprisingly often correct, hypothesis about the underlying issue or bug just from looking at the stacktraces and the involved types that users post on Slack or Github, without having to start a computer and to rerun their, possibly even incomplete, code. I think we should just try to capture common mistakes better so that users are only presented with a proper stacktrace when they find an actual bug - and then it's good if they can post the full information.

**Comment by devmotion** [comment]
I guess you could post it as a gist? I've never run into the character limit but I assume it is also one reason why according to the [Julia instructions](https://github.com/JuliaLang/julia/blob/bb5b98e72a151c41471d8cc14cacb495d647fb7f/doc/src/devdocs/backtraces.md) backtraces should be uploaded as a gist and linked to from a github issue.

**Comment by devmotion** [comment]
Maybe https://github.com/TuringLang/Turing.jl/pull/1841 already fixes your use cases without hiding any information.

**Comment by yebai** [comment]
Seems fixed by https://github.com/TuringLang/Turing.jl/pull/1841
