### ISSUE TITLE
Question: Which package is the MCMCserial() part of? been working through the notebook and have had problems with it not being defined hence that part of the notebook does not run

### ISSUE THREAD

**Issue by daany2** [TuringLang/Turing.jl#1842]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/10_bayesian-differential-equations.md

**Comment by devmotion** [comment]
`MCMCSerial` (with capital `S`) is defined in AbstractMCMC. But users don't have to know this since it is re-exported by Turing. That is, if you run `using Turing` it will be available and you can just use `MCMCSerial()`.

Maybe you use an old version of Turing (and/or AbstractMCMC) that did not define it? Can you make sure you use at least the versions that the tutorial was run with (https://turing.ml/dev/tutorials/10-bayesian-differential-equations/#appendix)?

**Comment by devmotion** [comment]
Did you manage to fix the problem?

**Comment by daany2** [comment]
Not yet, still having the problem. Updated to the newest Turing Version 0.21.1 but when I run the code it gives the same error. I installed AbstractMCMC too

**Comment by daany2** [comment]
[manifest.pdf](https://github.com/TuringLang/Turing.jl/files/8969001/manifest.pdf)

**Comment by daany2** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/107870537/175358732-74af9411-88fd-4ca7-ad3b-8a016ff41ae3.png)

**Comment by yebai** [comment]
Likely an issue of using out-of-date Turing releases. Please reopen if you still have questions.
