### ISSUE TITLE
Turing amends global data variables

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#208]
```julia
@model test(x) = begin
  push!(x, 4)
  x ~ MvNormal(...) # 4-dim multivariate normal
end

x = [1, 2, 3]
sample(test(x), ...)
```

will not work as expected because `x` is changed globally, and a new `1` is kept getting pushed into `x`.

**Comment by yebai** [comment]
That's true, I don't want to `deepcopy` data variables particularly for large datasets. Maybe we should warn the user not to modify `x` here.

**Comment by ChrisRackauckas** [comment]
>will not work as expected because x is changed globally, and a new 1 is kept getting pushed into x.

Well no, `x` is changed using its local reference even though it's a global. That's subtly different, but just a standard property of mutating functions in Julia since the value of an array is its reference (i.e. pass by reference and not by value). I don't think this needs to be documented as part of Turing.jl since it's what you'd expect throughout the language from any mutating function.
