### ISSUE TITLE
Beyond vectorisation?

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#283]
Seems that BLAS will give the best performance optimisation (especially for matrix ops), though it might not support AD (i guess)? Might be a future work if we need it.

Ref: JuliaCon 2016 | Introduction to Writing High Performance Julia (Workshop)
![image](https://cloud.githubusercontent.com/assets/5985769/26827607/f303c8ac-4ab5-11e7-9ed9-99ca6cddd9a0.png)

**Comment by ChrisRackauckas** [comment]
That video is slightly old.  BLAS supports AD since Julia's BLAS functions all have generic fallbacks. Setting everything up as vectorized operations and then using BLAS, views, GPUArrays, etc. is one way to go. The other is to manually devectorize everything that isn't a BLAS call and multithread those (along with `@inbounds` etc.). The latter is more optimized for the single case of just multithreading, but the former is better if GPUs actually matter. Whether GPUs matter depends on how big the problem is. You'll need at least like 1000x1000 matrices with a bunch of iterated matmuls for GPUs to actually speed this stuff up, so I wouldn't just assume GPUs are helpful in this domain.
