### ISSUE TITLE
Add more models to benchmarking

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#309]
Add models from the following folder to benchmarking

- https://github.com/goedman/Stan.jl/tree/master/Examples/NoMamba

**Comment by xukai92** [comment]
The first one https://github.com/goedman/Stan.jl/blob/master/Examples/NoMamba/ARM/Ch03/Kid/kidscore.jl Stan version is broken. They didn't even put a prior on their variables so CMDStan gives error about 

```
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: normal_lpdf: Scale parameter is nan, but must be > 0!  (in '/Users/kai/projects/Turing/Turing.jl/tmp/kid.stan' at line 12)
```

**Comment by xukai92** [comment]
Update

It seems that the folder `NoMamba` need to set `useMamba=false` for Stan so that their model can do maximumlikelihood?

**Comment by xukai92** [comment]
Update

Use HMC in that case in Stan gives a wrong answer (different from setting `useMamba=false`).
I managed to do a maximum likelihood in Turing.jl which gives a wrong answer.

**Comment by xukai92** [comment]
@yebai Do we still want the Bernoulli one?

**Comment by yebai** [comment]
> The first one https://github.com/goedman/Stan.jl/blob/master/Examples/NoMamba/ARM/Ch03/Kid/kidscore.jl Stan version is broken. They didn't even put a prior on their variables so CMDStan gives error about

Stan places a uniform prior on parameters without explicit prior specification, see 

https://stats.stackexchange.com/questions/37611/parameters-without-defined-priors-in-stan

**Comment by xukai92** [comment]
Yes. I added two helper distributions for that purpose in https://github.com/yebai/Turing.jl/pull/310/commits/ee09dd1bb9db5d55c97749ca68428c5bf67e3bf7, but still seems not get stable answer (actually even Stan doesn't, when sampler is set to HMC).

**Comment by xukai92** [comment]
All models are there now but:

- Kid model gives inconsistent results between Stan and Turing as well as Stan itself
  - Stan sometimes gives error "Exception: normal_lpdf: Scale parameter is nan, but must be > 0!" with static setting, while Turing is always fine because we rejected sample in that case (maybe not a good idea for debugging?)
- Dyes model has very peaky posterior
  - Turing seems to performs badly
  - Stan with static HMC also very bad but NUTS good
    - Cov pre-cond is important?
- Binomial model doesn't work
  - Need to fix https://github.com/yebai/Turing.jl/issues/311

**Comment by xukai92** [comment]
@yebai Can you have a look at those models with problems (commented above)?

**Comment by xukai92** [comment]
@yebai This is the issue that motivates me to introduce `Flat` (https://github.com/yebai/Turing.jl/issues/315). I've added file links in the comments above.
