### ISSUE TITLE
`add_sample!`: Correctness

### ISSUE THREAD

**Issue by wesselb** [TuringLang/Turing.jl#451]
If we're not mistaken, the updates performed in [`add_sample!`](https://github.com/TuringLang/Turing.jl/blob/6f144d41f815b0fb2c72b6e26228279931e42234/src/samplers/support/adapt.jl#L16) are

```
mu_{n+1} = n / (n + 1) mu_n + 1 / (n + 1) s,
M_{n+1}  = M_n + (s - mu_n) * (s - mu_{n+1})
         = M_n + n / (n + 1) (s - mu_n)^2.
```

Is mixing `mu_n` and `mu_{n+1}` in the update of `M_{n+1}` intended? The resulting sequence for `M` weights later samples more. In the limit, the estimate will indeed be unbiased:

```
Limit_{n -> Infinity} 1 / n Sum_{i = 1 ... n} i / (i + 1) = 1
```

However, for finite `n`, this seems to produce a biased estimate.

As a side note, we can reduce the number of allocations by performing in-place updates instead:

```julia
  δ = s .- ve.μ
  ve.μ .+= δ / ve.n
  ve.M .+= δ .* (s .- ve.μ)
```

**Comment by yebai** [comment]
@wesselb I think the code in `add_sample!` is intended. You're right that this code produces a biased estimator for the variance for finite n. However, since we only perform adaption for during a fixed warm-up period, the unbiasedness of the sampling algorithm is unaffected. 

Ps.  This procedure is known as the Welford method for computing variance. The Turing code is the same as the python implementation described [here](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Online_algorithm).

**Comment by yebai** [comment]
@wesselb could you create a PR for your suggested in-place updates? Many thanks.

**Comment by wesselb** [comment]
@yebai Thanks looking into this. That makes sense. I've created a PR with the in-place updates: [#455](https://github.com/TuringLang/Turing.jl/pull/455).

**Comment by yebai** [comment]
@wesselb @willtebbutt I've merged the PR - thanks!
