### ISSUE TITLE
HMC for models with dynamic dimentionality 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#498]
Excerpt from https://github.com/TuringLang/Turing.jl/issues/495

Later, we made a design decision that during an HMC step, the dimensionality of parameters assigned to HMC shouldn't change. However, the dimensionality of parameters assigned to HMC can still change for different HMC steps. For example, if a new parameter is created during an HMC iteration and is assigned to HMC, then before the current HMC iteration finishes, the newly created parameter is not updated. Therefore, the newly created parameter value will stay the same as its initialization (e.g. a draw from its prior). This design simplifies the HMC implementation and makes the code you are referring to obsolete.

@xukai92 could you take a look at HMC and see whether the design above is correctly implemented?

**Comment by xukai92** [comment]
I think the current code doesn't do what you described. This is because during one refactoring, we decide to assume the model is static during the whole HMC and, and we removed the code to **check whether a `VarName` is in `VarInfo`; if not, sample one** in `assume` (https://github.com/TuringLang/Turing.jl/blob/master/src/samplers/hmc.jl#L178-L188), but always fetch one from `VarInfo`. 

I could create a PR to pull that functionality back. Do you have a concrete model I could test on?

**Comment by mohamed82008** [comment]
Could be relevant: https://github.com/tpapp/DynamicHMC.jl

**Comment by xukai92** [comment]
When a parameter is used for some iterations, then omitted for a few iterations, and used again: do I resample it from prior, or I use the previously-stored value? Also is there any literature about HMC with dynamic dimension?

**Comment by xukai92** [comment]
I believe the proper way to do this is via reversible-jump. Gen can probably do that now.
