### ISSUE TITLE
Assume in loops and array type

### ISSUE THREAD

**Issue by hessammehr** [TuringLang/Turing.jl#507]
The following code seems to work fine:

```julia
alg = HMC(1000, 0.2, 4)

@model vdemo() = begin
  x = Vector{Real}(undef, N)
  for i = 1:N
    x[i] ~ Normal(0, sqrt.(4))
  end
end

t_loop = @elapsed res = sample(vdemo(), alg)
```

However, changing `Real` to `Float64` seems to make it break.

```julia
alg = HMC(1000, 0.2, 4)

@model vdemo() = begin
  x = Vector{Float64}(undef, N)
  for i = 1:N
    x[i] ~ Normal(0, sqrt.(4))
  end
end

t_loop = @elapsed res = sample(vdemo(), alg)
```

`ERROR: MethodError: no method matching Float64(::Flux.Tracker.TrackedReal{Float64})`

There seems to be an easy fix:
```julia
Float64(f::Flux.Tracker.TrackedReal{Float64}) = f.data
```

A few thoughts/questions:
- Is there a reason we use an abstract type `Real` instead of, e.g., `Float64`?
- Are we interested in adding the above shim?
- Why the broadcast in the `sqrt` call?

**Comment by yebai** [comment]
> Is there a reason we use an abstract type Real instead of, e.g., Float64?

This is required to make AD work. `Flux.Tracked` is a subtype of `Real`.

> Are we interested in adding the above shim?

I'm not sure cause it might cause incorrect gradients.

**Comment by yebai** [comment]
@xukai92 might be able to elaborate on this.

**Comment by xukai92** [comment]
I agree with @yebai on the first two answers. + I think doing `Float64(f::Flux.Tracker.TrackedReal{Float64}) = f.data` is against type piracy (https://docs.julialang.org/en/v1.0.0/manual/style-guide/#Avoid-type-piracy-1)?

> Why the broadcast in the sqrt call?

I don't think it's necessary to use broadcast here.

**Comment by willtebbutt** [comment]
Adding
```julia
Float64(f::Flux.Tracker.TrackedReal{Float64}) = f.data
```
will almost certainly cause AD to fail silently, so we should _definitely_ not do this.

**Comment by willtebbutt** [comment]
If the above `sqrt` broadcasting is something that is in one of our examples, then @hessammehr it would be good if you could make a PR to fix it. Otherwise we should close this issue.

**Comment by hessammehr** [comment]
@willtebbutt Will do.

@willtebbutt @xukai92 If you will indulge me, I was hoping to ask why the AD seems to handle `Real` just fine but chokes on `Float64`/`Float32`. Also wondering whether using an abstract type here has any performance implications.

**Comment by willtebbutt** [comment]
Ah, of course, happy to explain. It results from the way AD is currently implemented in Julia generally, as opposed to being something fundamental to AD, and has strong negative performance implications.  

Say we're computing the gradient of a function `f(x)`, then (reverse-mode) AD fundamentally needs to keep track of every operation that happens during programme execution that involves `x`. The way people have typically gone about this in Julia is to add extra types that contain the metadata necessary to do tracking. For example, Flux's `Tracker.TrackedReal` is a subtype of `Real` and contains a value, which is itself a concrete subtype of `Real`, and some extra information needed to perform tracking. This design is chosen in anticipation of `f` having been written in a generic enough manner that any subtype of `Real` can pass through it. When you create the concretely-typed `Vector{Float64}`, you can't place any arbitrary `Real` in it, so Flux is unable to propagate the information that it needs to through it. (The story is similar for ForwardDiff). When we get a Cassette-based AD, this should change, but this is the situation for now unfortunately.

You're also correct that it has significant performance implications, because a `Vector{Real}` isn't type stable. There's not really another way to write this code at the minute unfortunately using Turing.

**Comment by hessammehr** [comment]
@willtebbutt Thank you very much for the explanation. I think I understand the situation a lot better now. The `sqrt` issue has been fixed, so I am going to close this issue.
