### ISSUE TITLE
Logging in samplers / diagnosis statistics

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#599]
We currently using a dictionary called `info` to log statistics like *number of leapfrog steps per sample* and *number of model evaluation per sample* during HMC samplings. This is a hack and we'd like to refactor this part of code. So what kind of information do we really want to log, probably as a diagnosis purpose?

**Comment by cpfiffer** [comment]
I just saw this. Right now I think it's better to keep all the diagnostic stuff in the newer `chains.info` field, which is a `NamedTuple` that holds all kind of random stuff. I'd recommend maybe storing any chain-specific diagnostic information in something like `chainstats`, so that you could access it by calling `chain.info.chainstats`.

**Comment by xukai92** [comment]
Thanks! I will keep it in mind. This issue is mainly for "how to pass in-sampling info to outer function call", so that we can store them in chain.

**Comment by yebai** [comment]
it would be good to standardise terminology for these statistics, particularly for HMC;  

- `:treedepth__`, 
- `:energy__`, 
- `:divergent__`, 
- `:accept_stat__`, 
- `:n_leapfrog__`, 
- `:lp__`, 

and those used by adaption

- `:stepsize__ `
- `:inv_mass_mat__` (perhaps only diagonal elements)

Logging the trajectory for adaption (e.g. stepsize, and mass matrix) make debugging HMC a lot easier.

**Comment by yebai** [comment]
Fixed by #793
