### ISSUE TITLE
Distributions not compatible with AD (ForwardDiff/Flux.Tracker)

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#615]
- [ ] MvNormal (not working with Flux), see #511 
- [x] Poisson, see #614 
- [x] Binomial, see #600

**Comment by mohamed82008** [comment]
Three possible solutions:
1. Define our own version of these functions for ForwardDiff and Flux.Tracker types. These should ideally be in Distributions.jl with Requires.jl to avoid adding extra dependencies there, 
2. Make a pure Julia implementation of these distributions and PR them to Distributions.jl, or
3. Use finite difference autodiff by default as Optim.jl does using [DiffEqDiffTools.jl](https://github.com/JuliaDiffEq/DiffEqDiffTools.jl).

**Comment by willtebbutt** [comment]
> Make a pure Julia implementation of these distributions and PR them to Distributions.jl; Poisson at least seems to use ccall, or

At least for `MvNormal`, that the implementation isn't pure Julia actually isn't the issue. The implementation in `Distributions.jl` places very strong type constraints on the mean vector in particular. I made a start on rectifying this for `MvNormal`, see [this PR](https://github.com/JuliaStats/Distributions.jl/pull/798), but having now dug slightly further into the internals it looks like a reasonable amount of work would be required to properly sort things out without making breaking changes to `Distributions.jl`, which presumably isn't an option.

> Use finite difference autodiff by default as Optim.jl does using DiffEqDiffTools.jl.

I'm not keen on this because it's inaccurate in general, and not well suited to high-dimensional problems.

> Define our own version of these functions for ForwardDiff and Flux.Tracker types. These should ideally be in Distributions.jl to avoid type piracy, with Requires.jl to avoid adding extra dependencies there,

We've already got this for `Binomial` and #614 provides something sensible for `Poisson`, so if someone turns that into a PR (@cpfiffer ?) that should be straightforward to resolve. `MvNormal` will remain slightly tricky without some (potentially slightly awkward) refactoring of `Distributions.jl` though.

@yebai @mohamed82008 what are your thoughts?

**Comment by yebai** [comment]
I prefer the solution of fixing these issues on the `Distributions.jl` and `DiffRules` side, through either pure Julia implementation of `logpdf` functions or customised gradient rules. This way these changes can also be helpful for other packages such as `Mamba` and `Stheno`. 

On the short term, we can keep these (temporary) fixes including #600 #614  in the Turing repo and remove them after these issues are addressed in the Distributions and related AD packages.

**Comment by yebai** [comment]
duplicate of #717 and https://github.com/TuringLang/Turing.jl/issues/615
