### ISSUE TITLE
Turing.jl exports "plot"

### ISSUE THREAD

**Issue by dcarrera** [TuringLang/Turing.jl#692]
This is related to #155 which was apparently fixed and closed a year ago. Today I hit exactly the same issue with Turing. I installed Turing for the first time and when I tried to plot with PyPlot I immediately hit a conflict because Turing also exports a "plot" function.

**Comment by mohamed82008** [comment]
Hi Daniel,

Please note that you can work around the problem of 2 packages in Julia exporting the same name by preceding the function name with the module it is defined in, e.g. `PyPlot.plot`. `Turing.jl` reexports `MCMCChain.jl` which exports `Plots.plot`. `PyPlot.plot` is not the same as `Plots.plot` however you can use `PyPlot` as a backend in `Plots.jl` by calling `pyplot()` followed by `Plots.plot(...)` without having to call `using PyPlot`. Another way to work around this problem is to define: `const plot = PyPlot.plot` after you call `using Turing, PyPlot`. I hope this helps.

**Comment by dcarrera** [comment]
I know the difference between PyPlot and Plots. I use PyPlot because I strongly prefer it. I do not like Plots. An MCMC package should not be in the business of telling me which plotting package to use. I hope you will agree. Is this going to be fixed? The last message in #155 said that it was fixed, but your comment is making me wonder. That issue was closed almost a year ago. Did the developer team change its mind about fixing that issue or is this something I can fix by upgrading to the master branch?

**Comment by mohamed82008** [comment]
Btw, I personally prefer PyPlot too and I am a member of the developers team :) Personal preferences aside though, Plots.jl is used in MCMCChains.jl where convenience plotting recipes are defined. The re-exporting decision was made for MCMCChains as a whole in https://github.com/TuringLang/Turing.jl/pull/520 since many examples go like: `using Distributions, Turing, MCMCChains`, so after the re-export, users can just do `using Turing`. This can be convenient for some, but inconvenient for others who don't like all these names littering their namespace. Please note that the choice of a default is not us telling anyone what to use for plotting; it is extra functionality that's there if you need it. Really, the extra cost of using PyPlot is just this one line:
```julia
using PyPlot; const plot = PyPlot.plot
```
or alternatively:
```julia
using PyPlot; using PyPlot: plot
```
so you can go ahead and use it if you like. Any of these lines will tell Julia that `plot` is `PyPlot.plot` not `Plots.plot`.

**Comment by dcarrera** [comment]
FYI. I asked and they've resolved this upstream.

https://github.com/TuringLang/MCMCChains.jl/pull/39
