### ISSUE TITLE
ForwardDiff type error?

### ISSUE THREAD

**Issue by Red-Portal** [TuringLang/Turing.jl#716]
```sh
in _unsafe_setindex!, in typeassert, expected Float64, got ForwardDiff.Dual{Nothing,Float64,10}
```
I'm getting this error while using HMC.

```julia
    @turing.model LDA(x, K, α, β) = begin
        N, D = size(x)
        L = 5 # ordinal levels

        ϕ = Array{Float64, 3}(undef, L, D, K);
        for i in 1:D
            for j in 1:K
                ϕ[:, i, j] ~ Dirichlet(L, α)
            end
        end

        θ = Matrix{Float64}(undef, K, N)
        for i in 1:N
            θ[:,i] ~ Dirichlet(K, β)
        end

        marginals = reshape(reshape(ϕ, (L * D, K)) * θ,
                            (L, D, N))
        for i in 1:N
            for j in 1:D
                x[i, j] ~ CategoricalReal(marginals[:,j,i])
            end
        end
        return ϕ, θ
    end
```
This is the model I'm currently using.
The error is caused here.
```julia
ϕ[:, i, j] ~ Dirichlet(L, α)
```

Also, I experienced problems while using the vectorized notation.

```julia
ϕ = Array{Float64, 3}(undef, L * D, K);
ϕ ~ [Dirichlet(K, alpha)]
```
This causes a dimension error.
How can I correctly used the vectorized notation?

**Comment by cpfiffer** [comment]
The issue here comes from the fact that the values inside `θ = Matrix{Float64}(undef, K, N)` and `ϕ = Array{Float64, 3}(undef, L, D, K)` are constrained to be of type `Float64`. The automatic differentiation converts those values from `Float64` to `ForwardDiff.Dual{Nothing,Float64,10}`. 

You can fix this by changing `Float64` to `Real` in your array/matrix definition; use `θ = Matrix{Real}(undef, K, N)` and `ϕ = Array{Real, 3}(undef, L, D, K)` instead. 

As to the list comprehension, I'm not sure how exactly it works with matrices like that. You might benefit from changing `Array{Float64, 3}` to `Vector{Vector{Real}}` since`Dirichlet` is vector-valued.

Someone else might be more helpful (@trappmartin?) on the list comprehension side. I know there's been some discussion about improving it in the past (#604).

**Comment by Red-Portal** [comment]
@cpfiffer Thanks that fixed the issue. However after changing to `Real` instead of `Float64` I noticed serious performance degradation. Seems like the matrix-matrix product below is not performed in parallel.

```julia
reshape(ϕ, (L * D, K)) * θ
```
I do not have deep enough insight to judge this issue but seems like OpenBLAS gemm is not called when `Real` is used

**Comment by trappmartin** [comment]
You are correct, using `Real` will cause performance issues. I would not recommend this if not necessary.

You might be able to get away with something like this:
```Julia
θ = Vector{Vector}(undef, N)
for i in 1:N
    θ[i] ~ Dirichlet(K, β)
end
```

**Comment by Red-Portal** [comment]
That answers my question so I'll close this. Hope documentation on performance tips can be imrpoved

**Comment by v-a-s-a** [comment]
Hi @Red-Portal, I'm running into the same issue. Were you able to find a suitable workaround?

**Comment by cpfiffer** [comment]
The performant fix is in the [performance tips](https://turing.ml/dev/docs/using-turing/performancetips#make-your-model-type-stable) section of the docs. Does that help?

**Comment by v-a-s-a** [comment]
That does indeed solve it, thank you @cpfiffer!
