### ISSUE TITLE
Domain Error on Develpment Branch

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/Turing.jl#814]
I'm having a bit of trouble over on #793, using the branch [`csp/interface-pt2`](https://github.com/TuringLang/Turing.jl/tree/csp/interface-pt2), and I'm hoping @mohamed82008 can point out somewhere I might be going wrong.

Using the following:

```julia
using Turing

@model test(x) = begin
    mu ~ Normal(10,10)
    s ~ InverseGamma(2,3)
    x ~ Normal(mu, s)
end

chn1 = sample(test(1.0), HMC(0.01, 7), 10)
chn2 = sample(test(1.0), NUTS(2, 0.65), 100)
```

I get a domain error only on the `NUTS` sampler. I seem to have done something which draws a negative value when calculating `logpdf_with_trans`. Currently the reverse mode AD is failing, mostly because I haven't yet started on the changeover there. 

Tips or hints are useful. A lot of the HMC stuff has been shifted around a lot, so even just a general direction indicating when this domain error issue is likely to show up would be very useful to me.

**Comment by mohamed82008** [comment]
I will check.

**Comment by mohamed82008** [comment]
Which MCMCChains are you using?

**Comment by mohamed82008** [comment]
The problem seems to be that the wrong `sample_init!` is called. I believe this one should be called https://github.com/TuringLang/Turing.jl/blob/csp/interface-pt2/src/inference/hmc.jl#L166 but that one is called instead https://github.com/TuringLang/Turing.jl/blob/csp/interface-pt2/src/inference/hmc.jl#L353. The first one has the `link!` line which makes sure all the values live in the Eucledian space. The HMC sampler can then wander around however it likes during sampling. The second `sample_init!` doesn't have the `link!` call.

**Comment by mohamed82008** [comment]
Or maybe it is the correct one, but it is missing the `link!` bit.

**Comment by mohamed82008** [comment]
Adding:
```julia
# Convert to transformed space
if spl.selector.tag == :default
    link!(spl.state.vi, spl)
    runmodel!(model, spl.state.vi, spl)
end
```
seems to fix it.

**Comment by mohamed82008** [comment]
Keep in mind that when tag is not `:default`, the linking is still done but elsewhere.

**Comment by cpfiffer** [comment]
Excellent, thank you for the assist!
