### ISSUE TITLE
Adding versioning support for Documentation and Tutorials. 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#837]
Our current documentation and tutorials are generated by  `Documenter.jl` and `Jekyll`. The process is simple.

1. using [`Documenter.jl`](https://github.com/JuliaDocs/Documenter.jl)  to pull out `docstrings` and generates `markdown` files (broken after `docs` redesign)
2. uploading `markdown` files and related assets to Github under the [`gh-pages` ](https://github.com/TuringLang/Turing.jl/tree/gh-pages) branch. 

Step 2 is based on a Julia [script](https://github.com/TuringLang/Turing.jl/blob/master/docs/make-utils.jl), which is adapted from the `Documenter.jl`'s `git_push` function. 

One limitation of the current setup is the lack of versioning for docs, see, e.g. [Flux](https://fluxml.ai/Flux.jl/stable/). A possible (and simple) fix is to implement a small Julia function, which runs `Documenter.jl` on all Turing.jl releases and generates a directory structure similar to  https://github.com/FluxML/Flux.jl/tree/gh-pages/ before running `Jekyll`. This would allow `Jekyll` to create multiple versions of the documentation and tutorials. 

Some other possible improvements 

1. simplify the current build [script](https://github.com/TuringLang/Turing.jl/blob/master/docs/make-utils.jl), by replacing `update_homepage()` with the standard `Documenter.deploydocs()`. 
2. build the docs into HTML files using `jekyll build` before uploading them to `gh-pages`, this would allow offline reading.

**Comment by cpfiffer** [comment]
Currently, we have some additional pre- and post- processing that is done in the script `make-utils.jl`, which you can find [here](https://github.com/TuringLang/Turing.jl/blob/master/docs/make-utils.jl). 

The main things this script does is provided in two functions, `preprocess_markdown` and `postprocess_markdown`. We pre-process, run `Documenter`, and then post-process.

The basic steps in the pre-processing phase are 
1. Remove any markdown file's YAML header.
2. Store the YAML header for the post-processing phase.

In post-processing, the steps are
1. Write the YAML header back in to each markdown file.
2. Polish the `api.md` file by converting section names to a single line under a markdown header. I don't know how much we need this anymore, but it definitely improves the library appearance and navigation.

The entire reason I wrote the script was because `Documenter.jl` does _not_ play nice with YAML headers. Documenter kind of assumes you have a jumble of markdown documents that you decide where to place when you call `Documenter.make`, but because we have so much custom stuff going on with our website, we need to specify the mapping from each markdown file to the rendered file's location on the website using Jekyll's functionality.  

The design thesis here was to use Documenter only to include docstrings, a dynamic library page, and possibly some examples (which we don't really use anywhere, to my knowledge), while using all of Jekyll to do any web stuff we wanted. The `make-utils.jl` script basically enables full usage of both Jekyll and Documenter.jl without either of them stepping on eachother's toes.

**Comment by yebai** [comment]
Fixed by #884
